### ISSUE TITLE
Using Release tab for downloads

### ISSUE THREAD

**Issue by nschonni** [GoEddie/DacpacExplorer#5]
Noticed that you checked in the release binary in https://github.com/GoEddie/DacpacExplorer/blob/master/download/DacPacExplorer.zip
If you tag a release, you can add zips to the release page as described here https://help.github.com/articles/creating-releases/

**Comment by gwalkey** [comment]
Im sorry, Im still new here. Did I check in something of yours or Microsoft in my repo? I dont think so

**Comment by nschonni** [comment]
Nope, this was just a suggestion because adding binaries to Git makes the repository larger (and cloning/fetching slower). Just pointing out that there is an alternate way that will keep the repository smaller. Feel free to close.

**Comment by gwalkey** [comment]
I didnt add any to mine, so im not sure what trigged your email

thanks

**Comment by nschonni** [comment]
I was just browsing the repo and saw the download directory and the zip inside, so I opened this issue on GitHub (not an e-mail). I was just suggesting a method that works for GitHub, but i'm just going to close this.
